language: r
cache: packages


jobs:
  include:
  - r: bioc-devel
    os: linux
  - r: bioc-devel
    os: osx
    before_install:
      - brew update
      - rm '/usr/local/bin/gfortran'
      - brew install libgit2
  - r: bioc-release
    os: linux
    script:
      - R CMD build .
      - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
      - R CMD check ${PKG_TARBALL} --as-cran; CHECK_RET=$? ;
      - Rscript -e "library(BiocCheck); BiocCheck(\"${PKG_TARBALL}\", 'no-check-version-num'=TRUE)"
      - if [[ $CHECK_RET -ne 0 ]];
        then
          echo "R CMD check failed";
          check_fail;
          dump_logs;
          travis_terminate 1;
        fi
        - check_warnings
  - r: bioc-release
    os: osx
    before_install:
      - brew update
      - rm '/usr/local/bin/gfortran'
      - brew install libgit2
    script:
      - R CMD build .
      - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
      - R CMD check ${PKG_TARBALL} --as-cran; CHECK_RET=$? ;
      - export_rcheck_dir
      - Rscript -e "library(BiocCheck); BiocCheck(\"${PKG_TARBALL}\", 'no-check-version-num'=TRUE)"
      - Rscript -e "message(devtools::check_failures(path = \"${RCHECK_DIR}\"))"
      - if [[ $CHECK_RET -ne 0 ]];
        then
          echo "R CMD check failed";
          check_fail;
          dump_logs;
          travis_terminate 1;
        fi
        - check_warnings
  allow_failures:
    - r: bioc-release


bioc_required: true
bioc_check: true
warnings_are_errors: true

r_packages:
  - covr
  - faahKO

addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin
      - libhdf5-dev

after_success:
  - Rscript -e 'library(covr); codecov(line_exclusions = list("R/zzz.R", "R/peakPantheR_start_GUI.R"))'
