language: r
cache: packages

os:
  - linux
  - osx

jobs:
  include:
    - r: bioc-devel
    - r: bioc-release
      script:
        - Rscript -e "library(BiocCheck); BiocCheck(\"${PKG_TARBALL}\", 'no-check-version-num'=TRUE)"
  allow_failures:
    - r: bioc-release

bioc_required: true
bioc_check: true

r_packages:
  - covr
  - faahKO

addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin
      - libhdf5-dev

before_install:
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then rm '/usr/local/bin/gfortran'; fi"
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install libgit2; fi"

after_success:
  - Rscript -e 'library(covr); codecov(line_exclusions = list("R/zzz.R", "R/peakPantheR_start_GUI.R"))'
