language: r
cache: packages

jobs:
  include:
  - r: bioc-devel
    os: linux
  - r: bioc-devel
    os: osx
    before_install:
      - brew update
      - rm '/usr/local/bin/gfortran'
      - brew install libgit2
  - r: bioc-release
    os: linux
    script:
      - R CMD build .
      - Rscript -e "library(BiocCheck); BiocCheck(Sys.getenv("PKG_TARBALL", ""), 'no-check-version-num'=TRUE)"
  - r: bioc-release
    os: osx
    before_install:
      - brew update
      - rm '/usr/local/bin/gfortran'
      - brew install libgit2
    script:
      - R CMD build .
      - Rscript -e "library(BiocCheck); BiocCheck(Sys.getenv("PKG_TARBALL", ""), 'no-check-version-num'=TRUE)"
  allow_failures:
    - r: bioc-release


bioc_required: true
bioc_check: true

r_packages:
  - covr
  - faahKO

addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin
      - libhdf5-dev

after_success:
  - Rscript -e 'library(covr); codecov(line_exclusions = list("R/zzz.R", "R/peakPantheR_start_GUI.R"))'
