language: r
cache: packages

os:
  - linux

r:
  - bioc-devel
  - bioc-release
  - oldrel

matrix:
  allow_failures:
    - r: bioc-devel 

bioc_required: true

r_packages:
  - covr

addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin
      - libhdf5-dev

after_success:
  - Rscript -e 'library(covr); codecov(line_exclusions = "R/zzz.R")'
